SELECT A.TABLESPACE_NAME, ROUND(A.TOTAL_SIZE,0) TOTAL_MB, ROUND((A.TOTAL_SIZE-B.FREE_SIZE),0) USED_MB, ROUND(B.FREE_SIZE,0) FREE_MB, 
ROUND(((A.TOTAL_SIZE-B.FREE_SIZE)/A.TOTAL_SIZE)*100) USEDPCT
FROM (SELECT TABLESPACE_NAME,SUM(BYTES/(1024*1024)) TOTAL_SIZE
FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME) A,
(SELECT TABLESPACE_NAME,SUM(BYTES/(1024*1024)) FREE_SIZE
FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME) B
WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME
ORDER BY USEDPCT DESC;








