    
    SELECT   
    A.TABLESPACE_NAME AS TS_NAME, 
    D.MB_TOTAL AS TEMP_TOTAL_MB,
    SUM (A.USED_BLOCKS * D.BLOCK_SIZE) / 1024 / 1024 AS TEMP_USED_MB,
    D.MB_TOTAL - SUM (A.USED_BLOCKS * D.BLOCK_SIZE) / 1024 / 1024 AS TEMP_FREE_MB
     FROM     V$SORT_SEGMENT A,
      (
       SELECT   B.NAME, C.BLOCK_SIZE, SUM (C.BYTES) / 1024 / 1024 MB_TOTAL
	FROM     V$TABLESPACE B, V$TEMPFILE C
	 WHERE    B.TS#= C.TS#
	  GROUP BY B.NAME, C.BLOCK_SIZE
	   ) D
	   WHERE    A.TABLESPACE_NAME = D.NAME
   GROUP BY A.TABLESPACE_NAME, D.MB_TOTAL;
